### ISSUE TITLE
[ToDo] Frontend ToDo List

### ISSUE THREAD

**Issue by shleecloud** [codestates/LearnRegex#1]
### 유저 정보 모달 UserInfoModal
로그인 / 회원가입 / 비밀번호 찾기/ 회원가입 인증메일 / 회원 정보 수정 / 회원 정보 수정 결과 / 회원탈퇴 / 회원 탈퇴 의사 / 회원 탈퇴 결과

- [x] #16
- [x] #219 
- [x] #220
- [x] #221 
- [x] #17
- [x] #18
    - 페이지에 따라서 검사하는 영역 파라미터를 부여하고 검사 항목을 나눌 수 있음 (ex. 회원 가입은 전체 검사)
- [x] #137

### 로그인 SignIn
- [x] #119
- [x] #250
- [x] #258

### 회원 가입 SignUp
- [x] #21
- [x] #22
- [x] #23

### 비밀번호 찾기 FindPW 
- [x] #24
- [x] #25

### 회원 정보 수정 EditUserInfo
- [x] #26
- [x] #27
- [x] #223
- [x] #28

### 회원 탈퇴 DeleteUserInfo
- [x] #30

### 퀴즈 리스트 요소 QuizListElement
- [x] #40
    - 퀴즈 제목 / 닉네임 /  이 문제를 n명이 풀었습니다 - 서버 요청 받아오기 /  리스트로 들어왔을 때 서버에 요청을 보내고
- [x] #41

### 퀴즈 리스트 QuizList
- [x] #42
- [x] #43

### 퀴즈 풀기 SolveQuiz
- [x] #79
- [x] #80
- [x] #278

### 퀴즈 수정
- [x] #85
    - 내가 작성했는지 확인
    - EditQuiz 페이지로 이동
- [x] #86

### 퀴즈 삭제 
- [x] #87
    - QuizList 페이지로 이동

### 퀴즈 정답 모달 QuizAnswerModal
- [x] #88
- [x] #89

### 퀴즈 만들기 MakeQuiz
- [x] #64
- [x] #66
- [x] #69
    - 한 칸이라도 비워져있을 시 애니메이션 효과
- [x] #246
- [x] #65
- [x] #279

### 정규표현식
- [x] #90
- [x] #169
- [x] #172
- [x] #170

### 학습하기 Tutorial
- [x] #155
- [x] #70
- [ ] #93
- [ ] #94
- [x] #71
- [x] #72
- [x] #156
- [x] #157

### 네비게이션 Navigation
- [x] #36
- [x] #37
- [x] #38
- [x] #39

### 푸터 Footer
- [x] #45

### 퀴즈 양식 QuizForm 
- [x] #52
    - 퀴즈 풀기와 학습하기에서 가져옴 
    - 내가 이미 풀었는지 확인
    - 중복 요청실행이 되지 않도록 상태값을 갱신해야 함
 
### 뒤로가기 버튼 GoBackButton
- [x] #50

### 공용 스타일 
- [x] #54
    - UserInfoModal, QuizAnswerModal에서 가져옴
- [ ] #56
- [x] #57
- [ ] #58

### 스타일 협의
- [x] #263
    - 테마 색상
    - 컨테이너 여백
    - 글꼴
    - 단위
    - 반응형 단계
    - 반응형시 변경될 단위
    - 글로벌 스타일 정의

### 개별 스타일
- [x] #36
- [x] #37 
- [x] #45
- [x] #266
    - MyInfo
    - Modify MyInfo
- [x] #267
     - QuizList
     - SolveQuiz
     - MakeQuiz
     - EditQuiz
- [x] #268
    - SideHint
    - SideList

## 8. 랜딩 페이지
- [x] #247
- [x] #248
- [x] #249

## 9. Bugfix
- [x] [client] Bugfix/GET 요청 시 닉네임 데이터가 없을 때 isLogin 상태에서 nickname이 빈 문자열이 되는 이슈 (quizlist)
- [ ] [Client] Bugfix/브라우저 경고메세지 exhaustive-deps-warning 
    - [exhaustive-deps-warning 해결법
](https://kyounghwan01.github.io/blog/React/exhaustive-deps-warning/#_1-useeffect%E1%84%82%E1%85%A2-state%E1%84%85%E1%85%B3%E1%86%AF-%E1%84%82%E1%85%A5%E1%87%82%E1%84%8B%E1%85%A5%E1%84%8C%E1%85%AE%E1%86%B7)
- [ ] [Client] Bugfix/npm install 명령어 입력시 critical 취약점 (npm audit) 
- [ ] [Client] Bugfix/모달의 띄워진 상태에서 브라우저 뒤로가기해도 모달이 남아있음
- [x] #313
    - Answer 란에 올바른 정규표현식 작성
    - TestCase를 수정해서 직전에 작성한 Answer로 해결할 수 없게 수정
    - Answer 란을 클릭하지 않고 퀴즈 제출
- [x] #310
    - 퀴즈 수정 완료하고 QuizForm 페이지에서 뒤로가기를 누르면 EditQuiz 페이지로 이동했다가 곧바로 Quiz 페이지로 이동
 - [ ] [Client] Modify/퀴즈 삭제하고 1번 페이지로 이동

## 10. Advanced
- [ ] [Client] Modify/MakeQuiz 제목 15자 이상 공백이 없으면 break-word 옵션으로 변경
- [x] #44
- [x] #81
    - QuizList, SolveQuiz, 회원 정보 조회, 프로필 수정
- [ ] #19
- [ ] [Client] Feature/SolveQuiz 풀면 상호작용 버튼 추가
