### ISSUE TITLE
[client] Feat/Tutorial 리스트 기능 구현

### ISSUE THREAD

**Issue by EUNYUSEO** [codestates/LearnRegex#156]
### ISSUE
* Group:  `client`
* Type: `feature`
* Detail: Feat/Tutorial 리스트 사이드 메뉴 기능

### TODO
1. [x]  리스트 클릭시 해당 문제로 이동
2. [x]  해당 문제로 이동되면 리스트 메뉴 사라짐
3. [x]  `X` 아이콘 클릭시 리스트 메뉴 사라짐
3. [x]  초기화 버튼 클릭시 초기화 안내 alert 띄우기
4. [x]  초기화 버튼 클릭시 로컬스토리지에 저장된 answer 초기화
