### ISSUE TITLE
[client] Styled/LandingPage 페이지 구현

### ISSUE THREAD

**Issue by yeonjinkimm** [codestates/LearnRegex#248]
### ISSUE
* Group:  `client`
* Type:  `feature`
* Detail: HeroSection, InfoSection, DetailSection 구현하기

### TODO
1. [x] HeroSection에 동영상 추가
2. [x] InfoSection에 학습하기 페이지 소개
3. [x] InfoSection에 퀴즈 페이지 소개
4. [x] DetailSection에 학습하기, 퀴즈 상세 기능 소개
