### ISSUE TITLE
[client] Styled/UserInfo 관련 모달 UI 디자인 구현

### ISSUE THREAD

**Issue by EUNYUSEO** [codestates/LearnRegex#266]
### ISSUE
* Group:  `client`
* Type: `layout`, `css`
* Detail: UserInfo 관련 모달 UI 디자인 작업

### TODO
1. [x]  SignIn 모달
2. [x] SignUp 모달
3. [ ] 이메일 인증 모달
4. [ ] 인증 발송 안내 모달
5. [ ] 정보 변경 확인 모달
6. [ ] 회원 탈퇴 관련 모달
