### ISSUE TITLE
[client] Styled/학습하기 페이지 UI 작업

### ISSUE THREAD

**Issue by EUNYUSEO** [codestates/LearnRegex#268]
### ISSUE
* Group:  `client`
* Type: `layout`, `css`
* Detail: 학습하기 페이지 UI 작업

### TODO
1. [x]  전체적인 틀 잡기
2. [x] QuizForm UI 구현
3. [x]  SideHint UI 구현
4. [x] SideList UI 구현
