### ISSUE TITLE
[Client] Feat/ Task,Text 구조의 문제풀기 양식 구현 (Advanced)

### ISSUE THREAD

**Issue by shleecloud** [codestates/LearnRegex#278]
### ISSUE
* Group:  `Client`
* Type: `Feature`
* Detail: Feat/ Task,Text 구조의 문제풀기 양식 구현 (Advanced)
### 내용
RegexOne 페이지 기반

### TODO
1. [x] Match 작업 구현
2. [x] Skip 작업 구현
3. [x] Capture 작업 구현
4. [x] Tutorial 내부 데이터 구조 변경
5. [x] Quiz 데이터베이스 구조 변경
