### ISSUE TITLE
[client] Styled/모달 UI 디자인 구현

### ISSUE THREAD

**Issue by EUNYUSEO** [codestates/LearnRegex#286]
### ISSUE
* Group:  `Client`
* Type: `Style`
* Detail: 로그인, 회원가입 제외 UserInfo 관련 모달 디자인 구현

### TODO
1. [x]  이메일 인증 모달
1. [x]  인증 발송 안내 모달
1. [x]  정보 변경 확인 모달
1. [x]  회원 탈퇴 관련 모달

### Delay
* 아이콘 자료 찾고 적용하는데 시간이 오래 걸렸다..
