### ISSUE TITLE
[Client] Bugfix/ 네비게이션에 닉네임 유지

### ISSUE THREAD

**Issue by EUNYUSEO** [codestates/LearnRegex#298]
### ISSUE
* Group:  `Client`
* Type: `Bugfix`
* Detail: 로그인했을 때 네비게이션에 닉네임 유지

### TODO
1. [x]  `SET_IS_LOGIN` 모듈에서 `isLogin`, `nickname` 분리해서 액션 생성 함수 생성
2. [x]  맞춰서 리듀서 재정의
3. [x]  `checkIsLogin` 함수에서 응답 받은 데이터에 맞게 `dispatch` 진행
