### ISSUE TITLE
[Server] Modify/TestCaseTarget 컬럼 확인 삭제

### ISSUE THREAD

**Issue by shleecloud** [codestates/LearnRegex#302]
### ISSUE
* Group:  `Client`
* Type: `Modify`
* Detail: TestCaseTarget 컬럼 확인 삭제
### TODO
1. [x] 퀴즈 만들기 TestCaseTarget 컬럼 확인 삭제
2. [x] 퀴즈 수정하기 TestCaseTarget 컬럼 확인 삭제
3. [x] 클라이언트 TestCaseTarget 항목 삭제
