### ISSUE TITLE
[Client] Bugfix/QuizForm/MakeQuiz 뒤로가기 이슈

### ISSUE THREAD

**Issue by shleecloud** [codestates/LearnRegex#310]
### ISSUE
* Group:  `Client`
* Type: `Feature`
* Detail: MakeQuiz 뒤로가기 이슈
### 내용
MakeQuiz 뒤로가기 동작과 SolveQuiz 뒤로가기 동작이 사용자가 의도한대로 동작하지 않음
`window.history.back` 으로 돌아가다보니 퀴즈 수정을 완료하고 뒤로가기 버튼을 누르면 퀴즈 수정페이지로 이동함

```js
export default function BackButton({ id = '0' }) {
  const historyBack = () => {
    // if (id === '0') window.location.replace('/quizlist');
    // else window.location.replace(`/quiz/${id}`);
    if (id === '0') window.location.href = '/quizlist';
    else window.location.href = `/quiz/${id}`;
  };

  return (
    <>
      <ImArrowLeft2 size="50" onClick={historyBack} />
    </>
  );
}

```

### TODO
1. [x]  BackButton 컴포넌트에 이동할 페이지 ID 상속, href로 동작 변경
2. [x]  SolveQuiz -> QuizList로 이동 (id=0)
3. [x]  InputQuiz -> Quiz로 이동(id={data ? data.id : '0'})
