### ISSUE TITLE
[client] Feat/Tutorial 사이드 메뉴 기능 구현

### ISSUE THREAD

**Issue by shleecloud** [codestates/LearnRegex#72]
### ISSUE
* Group:  `client`
* Type: `feature`
* Detail: Tutorial 사이드 메뉴 기능
   - 화살표 클릭시 각 상황에 맞게 리스트 이동
   - 리스트 아이콘 클릭시 리스트 사이드 메뉴 표시

### TODO
1. [x]  화살표 클릭시 이전, 혹은 다음 리스트로 이동
2. [x]  이동에 맞게 레벨 표시 다르게 보여주기
3. [x]  리스트 아이콘 클릭하면 리스트 메뉴 보여주기
