### ISSUE TITLE
[client] Feat/SolveQuiz 삭제

### ISSUE THREAD

**Issue by EUNYUSEO** [codestates/LearnRegex#87]
### ISSUE
* Group:  `client`
* Type: `feature`
* Detail: 퀴즈 - 문제 풀기 페이지에서 삭제 클릭 시 퀴즈 삭제

### TODO
1. [x]  삭제 클릭시 서버에게 DELETE 요청
2. [x]  삭제 되었다는 알람 띄우기
3. [x]  삭제 성공시 퀴즈 리스트 페이지로 전환
